# Generated by Django 4.0.1 on 2022-01-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='battedBallData',
            fields=[
                ('BATTER_ID', models.IntegerField()),
                ('BATTER', models.TextField()),
                ('PITCHER_ID', models.IntegerField()),
                ('PITCHER', models.TextField()),
                ('GAME_DATE', models.TextField()),
                ('LAUNCH_ANGLE', models.FloatField()),
                ('EXIT_SPEED', models.FloatField()),
                ('EXIT_DIRECTION', models.FloatField()),
                ('HIT_DISTANCE', models.FloatField()),
                ('HANG_TIME', models.FloatField()),
                ('HIT_SPIN_RATE', models.FloatField()),
                ('PLAY_OUTCOME', models.TextField()),
                ('VIDEO_LINK', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
    ]
